image: java:latest

before_script:
  - export TEST_LIB_PATH="lib-test"
  - export TEST_BIN_PATH="bin-test"
  - export TEST_SRC_PATH="src-test"
  - export TEST_CLASS_PATH="./$TEST_LIB_PATH/*;./$TEST_BIN_PATH;."
  - export FIND_AND_REPLACE="s/^$TEST_SRC_PATH.//g"
  - export TESTS=$(find $TEST_SRC_PATH/ -name "Test*.java" | sed 's/\//./g' | sed 's/.java$//g' | sed $FIND_AND_REPLACE)

build:
  stage: build
  script: 
    - rm -rf $TEST_BIN_PATH
    - mkdir $TEST_BIN_PATH
    - rm -rf $TEST_LIB_PATH
    - mkdir $TEST_LIB_PATH
    - sh ./download_dependency.sh $TEST_LIB_PATH
    - javac -g -classpath $TEST_CLASS_PATH -d $TEST_BIN_PATH/ $(find $TEST_SRC_PATH/ -name "*.java") $(find src-presentation/ -name "*.java") $(find src-domain/ -name "*.java") $(find src-data/ -name "*.java")
 
  
test:
  stage: test
  script: 
    - java -cp $TEST_CLASS_PATH org.junit.runner.JUnitCore $TESTS
    - rm -rf $TEST_BIN_PATH
    - rm -rf $TEST_LIB_PATH
