image: java:8
  
stages:
  - dependency
  - compile
  - test
  
dependency:
  stage: dependency
  script:
    - rm -rf lib-test
    - mkdir lib-test
    - sh ./download_dependency.sh lib-test
  artifacts:
    paths:
    - lib-test/
    expire_in: 30 minutes

compile:
  stage: compile
  script: 
    - ls lib-test
    - rm -rf bin-test
    - mkdir bin-test
    - javac -cp ".:lib-test/*" -d bin-test/ $(find src-test/ -name "*.java") $(find src-presentation/ -name "*.java") $(find src-domain/ -name "*.java") $(find src-data/ -name "*.java") 
  artifacts:
    paths:
    - bin-test/
    expire_in: 30 minutes
  
test:
  stage: test
  script: 
    - java -cp ".:./lib-test/*:bin-test/" org.junit.runner.JUnitCore $(find src-test/ -name "Test*.java" | sed 's/\//./g' | sed 's/.java$//g' | sed 's/^src-test.//g')
    
