image: java:8

before_script:
  - export TEST_LIB_PATH="lib-test"
  - export TEST_BIN_PATH="bin-test"
  - export TEST_SRC_PATH="src-test"
  
stages:
  - dependency
  - compile
  - test
  
dependency:
  stage: dependency
  script:
    - rm -rf $TEST_LIB_PATH
    - mkdir $TEST_LIB_PATH
    - sh ./download_dependency.sh $TEST_LIB_PATH
  artifacts:
    paths:
    - $TEST_LIB_PATH

compile:
  stage: compile
  script: 
    - rm -rf $TEST_BIN_PATH
    - mkdir $TEST_BIN_PATH
    - javac -cp ".:$TEST_LIB_PATH/*" -d $TEST_BIN_PATH/ $(find $TEST_SRC_PATH/ -name "*.java") $(find src-presentation/ -name "*.java") $(find src-domain/ -name "*.java") $(find src-data/ -name "*.java") 
  artifacts:
    paths:
    - bin-test/
  
test:
  stage: test
  script: 
    - export FIND_AND_REPLACE="s/^$TEST_SRC_PATH.//g"
    - export TESTS=$(find $TEST_SRC_PATH/ -name "Test*.java" | sed 's/\//./g' | sed 's/.java$//g' | sed $FIND_AND_REPLACE)
    - java -cp ".:./$TEST_LIB_PATH/*:$TEST_BIN_PATH/" org.junit.runner.JUnitCore $TESTS
    
